services:
  - type: web
    name: ganapati-stall
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: ADMIN_PASSWORD
        value: ganesh123
